Downloading data from https://storage.googleapis.com/tensorflow/keras-applications/convnext/convnext_small_notop.h5
198551472/198551472 [==============================] - 9s 0us/step
Downloading data from https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz
170498071/170498071 [==============================] - 196s 1us/step
2023-04-13 09:36:20.913213: W tensorflow/tsl/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
Epoch 1/10
2023-04-13 09:36:37.774839: I tensorflow/compiler/xla/service/service.cc:173] XLA service 0x2e7671330 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2023-04-13 09:36:37.774862: I tensorflow/compiler/xla/service/service.cc:181]   StreamExecutor device (0): Host, Default Version
2023-04-13 09:36:37.880868: I tensorflow/compiler/jit/xla_compilation_cache.cc:477] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.
1563/1563 [==============================] - ETA: 0s - loss: 0.7936 - accuracy: 0.7388     
Epoch 1: val_loss improved from inf to 0.68132, saving model to part2_model_best.h5
1563/1563 [==============================] - 2915s 2s/step - loss: 0.7936 - accuracy: 0.7388 - val_loss: 0.6813 - val_accuracy: 0.7798
Epoch 2/10
1563/1563 [==============================] - ETA: 0s - loss: 0.4937 - accuracy: 0.8405   
Epoch 2: val_loss improved from 0.68132 to 0.60556, saving model to part2_model_best.h5
1563/1563 [==============================] - 2579s 2s/step - loss: 0.4937 - accuracy: 0.8405 - val_loss: 0.6056 - val_accuracy: 0.8068
Epoch 3/10
1563/1563 [==============================] - ETA: 0s - loss: 0.3684 - accuracy: 0.8794   
Epoch 3: val_loss improved from 0.60556 to 0.58380, saving model to part2_model_best.h5
1563/1563 [==============================] - 2535s 2s/step - loss: 0.3684 - accuracy: 0.8794 - val_loss: 0.5838 - val_accuracy: 0.8212
Epoch 4/10
1563/1563 [==============================] - ETA: 0s - loss: 0.2891 - accuracy: 0.9056   
Epoch 4: val_loss improved from 0.58380 to 0.58114, saving model to part2_model_best.h5
1563/1563 [==============================] - 2546s 2s/step - loss: 0.2891 - accuracy: 0.9056 - val_loss: 0.5811 - val_accuracy: 0.8310
Epoch 5/10
1563/1563 [==============================] - ETA: 0s - loss: 0.2252 - accuracy: 0.9272   
Epoch 5: val_loss improved from 0.58114 to 0.57877, saving model to part2_model_best.h5
1563/1563 [==============================] - 2529s 2s/step - loss: 0.2252 - accuracy: 0.9272 - val_loss: 0.5788 - val_accuracy: 0.8362
Epoch 6/10
1545/1563 [============================>.] - ETA: 2:46 - loss: 0.1785 - accuracy: 0.9417Traceback (most recent call last):
  File "/path-to-project-folder-on-local-machine/CIS6261-Project-SP23/train.py", line 76, in <module>
    train_model(model, (train_x, train_y), (val_x, val_y), (test_x, test_y))
  File "/path-to-project-folder-on-local-machine/CIS6261-Project-SP23/train.py", line 48, in train_model
    history = model.fit(
  File "/path-to-project-folder-on-local-machine/rohanp-initial/env/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/path-to-project-folder-on-local-machine/rohanp-initial/env/lib/python3.10/site-packages/tensorflow/python/eager/execute.py", line 52, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: Graph execution error:

Detected at node 'truediv_657' defined at (most recent call last):
    File "/path-to-project-folder-on-local-machine/CIS6261-Project-SP23/train.py", line 76, in <module>
      train_model(model, (train_x, train_y), (val_x, val_y), (test_x, test_y))
    File "/path-to-project-folder-on-local-machine/CIS6261-Project-SP23/train.py", line 48, in train_model
      history = model.fit(
    File "/path-to-project-folder-on-local-machine/rohanp-initial/env/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "/path-to-project-folder-on-local-machine/rohanp-initial/env/lib/python3.10/site-packages/keras/engine/training.py", line 1650, in fit
      tmp_logs = self.train_function(iterator)
    File "/path-to-project-folder-on-local-machine/rohanp-initial/env/lib/python3.10/site-packages/keras/engine/training.py", line 1249, in train_function
      return step_function(self, iterator)
    File "/path-to-project-folder-on-local-machine/rohanp-initial/env/lib/python3.10/site-packages/keras/engine/training.py", line 1233, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/path-to-project-folder-on-local-machine/rohanp-initial/env/lib/python3.10/site-packages/keras/engine/training.py", line 1222, in run_step
      outputs = model.train_step(data)
    File "/path-to-project-folder-on-local-machine/rohanp-initial/env/lib/python3.10/site-packages/keras/engine/training.py", line 1027, in train_step
      self.optimizer.minimize(loss, self.trainable_variables, tape=tape)
    File "/path-to-project-folder-on-local-machine/rohanp-initial/env/lib/python3.10/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 527, in minimize
      self.apply_gradients(grads_and_vars)
    File "/path-to-project-folder-on-local-machine/rohanp-initial/env/lib/python3.10/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 1140, in apply_gradients
      return super().apply_gradients(grads_and_vars, name=name)
    File "/path-to-project-folder-on-local-machine/rohanp-initial/env/lib/python3.10/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 634, in apply_gradients
      iteration = self._internal_apply_gradients(grads_and_vars)
    File "/path-to-project-folder-on-local-machine/rohanp-initial/env/lib/python3.10/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 1166, in _internal_apply_gradients
      return tf.__internal__.distribute.interim.maybe_merge_call(
    File "/path-to-project-folder-on-local-machine/rohanp-initial/env/lib/python3.10/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 1216, in _distributed_apply_gradients_fn
      distribution.extended.update(
    File "/path-to-project-folder-on-local-machine/rohanp-initial/env/lib/python3.10/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 1213, in apply_grad_to_update_var
      return self._update_step(grad, var)
    File "/path-to-project-folder-on-local-machine/rohanp-initial/env/lib/python3.10/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 224, in _update_step
      self.update_step(gradient, variable)
    File "/path-to-project-folder-on-local-machine/rohanp-initial/env/lib/python3.10/site-packages/keras/optimizers/optimizer_experimental/adam.py", line 200, in update_step
      variable.assign_sub((m * alpha) / (tf.sqrt(v) + self.epsilon))
Node: 'truediv_657'
Incompatible shapes: [0] vs. [3072,768]
         [[{{node truediv_657}}]] [Op:__inference_train_function_57699]